rest_command:
  push_display:
    url: "http://10.0.4.20/api/display/draw"
    method: POST
    content_type: "application/json"
    payload: >
      {
        "application_name": "my_app",
        "led_notification_color": "#FF0000FF",
        "elements": [
          {
            "id": "0",
            "timeout": 0,
            "align": "center",
            "x": 16,
            "y": 8,
            "type": "text",
            "text": "Powered by Home Assistant! Time: {{ now().strftime('%H:%M') }} Weather: {{ state_attr('weather.forecast_home', 'temperature') }}° {{ states('weather.forecast_home') }}",
            "font": "normal",
            "color": "#FFFFFFFF",
            "width": 128,
            "scroll_rate": 1000,
            "scroll_start_delay": 0,
            "scroll_repeat_delay": 0,
            "display": "front"
          }
        ]
      }
